[tox]
skipsdist = True
usedevelop = True
skip_missing_interpreters = True

envlist = 
    py39-dj42-wt{52,63,70}-{sqlite,postgres,mysql}
    py{310,311,312,313}-dj{51,52}-wt{63,70}-{sqlite,postgres,mysql}
    
[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[gh-actions:env]
DATABASE = 
    sqlite: sqlite
    postgres: postgres
    mysql: mysql

[testenv]
install_command = pip install -e ".[testing]" -U {opts} {packages}

commands = 
    coverage run manage.py test --deprecation all
    coverage report -m

deps =
    coverage

    dj42: Django>=4.2,<4.3
    dj51: Django>=5.1,<5.2
    dj52: Django>=5.2,<5.3

    wt52: Wagtail>=5.2,<5.3
    wt63: Wagtail>=6.3,<6.4
    wt70: Wagtail>=7.0,<7.1

    postgres: psycopg2
    mysql: mysqlclient

[flake8]
ignore = D203
exclude = .git,__pycache__,docs/,old,build,dist,bin/*
max-complexity = 10
max-line-length = 120

[isort]
profile = black
multi_line_output = 3
